export enum FLOWS {
  AUTH_FLOW = 'AUTH_FLOW',
  PRODUCT_FLOW = 'PRODUCT_FLOW',
}

export enum AUTH_SCREENS {
  LOGIN = 'LOGIN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
}

export enum PRODUCT_SCREENS {
  PRODUCT_LIST = 'PRODUCT_LIST',
}
